#!/bin/bash

source "$(dirname $0)/vars"

case "$1" in
  elasticsearch:create)
    elasticsearch_for_app "$2"
    verify_max_args 2 "$@"

    touch "$DB_VOLUME"
    info "elasticsearch database created: $DB_CONTAINER"
    redeploy_app "$APP"
    ;;

  elasticsearch:delete|elasticsearch:destroy)
    elasticsearch_for_app "$2"
    verify_max_args 2 "$@"

    stop_and_remove_container "$DB_CONTAINER" "$DB_DATA_CONTAINER"
    rm -f "$DB_VOLUME"
    info "elasticsearch database deleted: $DB_CONTAINER"
    redeploy_app "$APP"
    ;;

  elasticsearch:info)
    elasticsearch_for_app "$2"
    verify_max_args 2 "$@"

    [[ ! -f "$DB_VOLUME" ]] && fail "$DB_CONTAINER: database is not linked to $APP"

    echo
    cat <<EOF
echo "       Host: $DB_HOST"
echo "       Port: $DB_PORT"
echo
echo "       ELASTICSEARCH_URL=$DB_URL"
EOF
    echo
    ;;

  help)
    cat && cat<<EOF
    elasticsearch:create <app>          Create a Elasticsearch database
    elasticsearch:delete <app>          Delete specified Elasticsearch database
    elasticsearch:info <app>            Display application information
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
