#!/bin/bash

source "$(dirname $0)/vars"

cat

case "$1" in
  elasticsearch:create)
    elasticsearch_for_app "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  elasticsearch:info)
    elasticsearch_for_app "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

esac
