#!/bin/bash

source "$(dirname $0)/../dokku_common"

DB_ROOT="$DOKKU_ROOT/.elasticsearch"
DB_IMAGE="${ELASTICSEARCH_IMAGE:-jumski/dokku-alt-elasticsearch}"
DB_CONTAINER_LINK="elasticsearch"
DB_CONTAINER_VOLUME="${ELASTICSEARCH_CONTAINER_VOLUME:-/var/lib/elasticsearch}"
DB_PORT="${ELASTICSEARCH_PORT:-9200}"
DB_COMMAND="${ELASTICSEARCH_COMMAND:-/usr/bin/start_elasticsearch}"

function elasticsearch_for_app() {
  verify_app_name "$1"
  DB_VOLUME="$DB_ROOT/$APP"
  DB_CONTAINER="elasticsearch_app_$APP"
  DB_DATA_CONTAINER="elasticsearch_data_$APP"
  DB_HOST="$DB_CONTAINER_LINK"
  DB_URL="http://$DB_CONTAINER_LINK:$DB_PORT"
}

function start_database_container() {
  docker run --name="$DB_DATA_CONTAINER" \
             -v "$DB_CONTAINER_VOLUME" \
             busybox:latest true 1>/dev/null 2>/dev/null || true

	docker run --detach \
             --name="$DB_CONTAINER" \
             --volumes-from="$DB_DATA_CONTAINER" \
             "$DB_IMAGE" \
             "$DB_COMMAND" >/dev/null
}

function ensure_database_container_is_running() {
  remove_container "$DB_CONTAINER"
  start_database_container 2>/dev/null || true
}
